package pt.afsmeira.ffadventuresheet.db

import pt.afsmeira.ffadventuresheet.model.Book
import pt.afsmeira.ffadventuresheet.model.BookStat
import pt.afsmeira.ffadventuresheet.model.Stat
import pt.afsmeira.ffadventuresheet.model.Stat.PossibleValues.*
import pt.afsmeira.ffadventuresheet.model.Stat.Type.*

/**
 * The initial state for [FFAdventureSheetDatabase].
 */
object InitialState {

    val books: List<Book> = listOf(
        Book(name = "The Warlock of Firetop Mountain",    coverUrl = "https://www.fightingfantasycollector.co.uk/FF1_Original.jpg"),
        Book(name = "The Citadel of Chaos",               coverUrl = "https://www.fightingfantasycollector.co.uk/FF2_Original.jpg"),
        Book(name = "The Forest of Doom",                 coverUrl = "https://www.fightingfantasycollector.co.uk/FF_Original.jpg"),
        Book(name = "Starship Traveller",                 coverUrl = "https://www.fightingfantasycollector.co.uk/FF3_Original.jpg"),
        Book(name = "City of Thieves",                    coverUrl = "https://www.fightingfantasycollector.co.uk/FF5_Original.jpg"),
        Book(name = "Deathtrap Dungeon",                  coverUrl = "https://www.fightingfantasycollector.co.uk/FF6_Original.jpg"),
        Book(name = "Island of the Lizard King",          coverUrl = "https://www.fightingfantasycollector.co.uk/FF7_Original.jpg"),
        Book(name = "Scorpion Swamp",                     coverUrl = "https://www.fightingfantasycollector.co.uk/FF8_ZigZag.jpg"),
        Book(name = "Caverns of the Snow Witch",          coverUrl = "https://www.fightingfantasycollector.co.uk/FF9_Zigzag.jpg"),
        Book(name = "House of Hell",                      coverUrl = "https://www.fightingfantasycollector.co.uk/FF10_zigzag.jpg"),
        Book(name = "Talisman of Death",                  coverUrl = "https://www.fightingfantasycollector.co.uk/FF11_ZigZag.jpg"),
        Book(name = "Space Assassin",                     coverUrl = "https://www.fightingfantasycollector.co.uk/FF12_ZigZag.jpg"),
        Book(name = "Freeway Fighter",                    coverUrl = "https://www.fightingfantasycollector.co.uk/FF13_ZigZag.jpg"),
        Book(name = "Temple of Terror",                   coverUrl = "https://www.fightingfantasycollector.co.uk/FF14_ZigZag.jpg"),
        Book(name = "The Rings of Kether",                coverUrl = "https://www.fightingfantasycollector.co.uk/FF15_Zigzag.jpg"),
        Book(name = "Seas of Blood",                      coverUrl = "https://www.fightingfantasycollector.co.uk/FF16_Zigzag.jpg"),
        Book(name = "Appointment with F.E.A.R.",          coverUrl = "https://www.fightingfantasycollector.co.uk/FF17_Zigzag.jpg"),
        Book(name = "Rebel Planet",                       coverUrl = "https://www.fightingfantasycollector.co.uk/FF18_Zigzag.jpg"),
        Book(name = "Demons of the Deep",                 coverUrl = "https://www.fightingfantasycollector.co.uk/FF19_Zigzag.jpg"),
        Book(name = "Sword of the Samurai",               coverUrl = "https://www.fightingfantasycollector.co.uk/FF20_Zigzag.jpg"),
        Book(name = "Trial of Champions",                 coverUrl = "https://www.fightingfantasycollector.co.uk/FF21_Zigzag.jpg"),
        Book(name = "Robot Commando",                     coverUrl = "https://www.fightingfantasycollector.co.uk/FF22_Zigzag.jpg"),
        Book(name = "Masks of Mayhem",                    coverUrl = "https://www.fightingfantasycollector.co.uk/FF23_ZigZag.jpg"),
        Book(name = "Creature of Havoc",                  coverUrl = "https://www.fightingfantasycollector.co.uk/FF24_Zigzag.jpg"),
        Book(name = "Beneath Nightmare Castle",           coverUrl = "https://www.fightingfantasycollector.co.uk/FF25_Dragon_Both.jpg"),
        Book(name = "Crypt of the Sorcerer",              coverUrl = "https://www.fightingfantasycollector.co.uk/FF26_Dargon_Both.jpg"),
        Book(name = "Star Strider",                       coverUrl = "https://www.fightingfantasycollector.co.uk/FF27_Dragon_both.jpg"),
        Book(name = "Phantoms of Fear",                   coverUrl = "https://www.fightingfantasycollector.co.uk/FF28_Dragon_both.jpg"),
        Book(name = "Midnight Rogue",                     coverUrl = "https://www.fightingfantasycollector.co.uk/FF29_Dargon_Both.jpg"),
        Book(name = "Chasms of Malice",                   coverUrl = "https://www.fightingfantasycollector.co.uk/FF30_Dragon_Both.jpg"),
        Book(name = "Battleblade Warrior",                coverUrl = "https://www.fightingfantasycollector.co.uk/FF31_Dragon_Front.jpg"),
        Book(name = "Slaves of the Abyss",                coverUrl = "https://www.fightingfantasycollector.co.uk/FF32_Dragon_Both.jpg"),
        Book(name = "Sky Lord",                           coverUrl = "https://www.fightingfantasycollector.co.uk/FF33_Dragon_Both.jpg"),
        Book(name = "Stealer of Souls",                   coverUrl = "https://www.fightingfantasycollector.co.uk/FF34_Dragon_front.jpg"),
        Book(name = "Daggers of Darkness",                coverUrl = "https://vignette2.wikia.nocookie.net/fightingfantasy/images/1/19/Figfan35.jpg"),
        Book(name = "Armies of Death",                    coverUrl = "https://www.fightingfantasycollector.co.uk/FF36_Dragon_Both.jpg"),
        Book(name = "Portal of Evil",                     coverUrl = "https://www.fightingfantasycollector.co.uk/FF37_Dragon_Spine.jpg"),
        Book(name = "Vault of the Vampire",               coverUrl = "https://www.fightingfantasycollector.co.uk/FF38_Dragon_Spine.jpg"),
        Book(name = "Fangs of Fury",                      coverUrl = "https://www.fightingfantasycollector.co.uk/FF39_Dragon_spine.jpg"),
        Book(name = "Dead of Night",                      coverUrl = "https://www.fightingfantasycollector.co.uk/FF40_Dragon_Spine.jpg"),
        Book(name = "Master of Chaos",                    coverUrl = "https://www.fightingfantasycollector.co.uk/FF41_Dargon_Spine.jpg"),
        Book(name = "Black Vein Prophecy",                coverUrl = "https://www.fightingfantasycollector.co.uk/FF42_Dragon_Spine.jpg"),
        Book(name = "The Keep of the Lich-Lord",          coverUrl = "https://www.fightingfantasycollector.co.uk/FF43_Dragon_spine.jpg"),
        Book(name = "Legend of the Shadow Warriors",      coverUrl = "https://www.fightingfantasycollector.co.uk/FF44_Dragon_Spine.jpg"),
        Book(name = "Spectral Stalkers",                  coverUrl = "https://www.fightingfantasycollector.co.uk/FF45_Dragon_spine.jpg"),
        Book(name = "Tower of Destruction",               coverUrl = "https://www.fightingfantasycollector.co.uk/FF46.jpg"),
        Book(name = "The Crimson Tide",                   coverUrl = "https://www.fightingfantasycollector.co.uk/FF47_Black_Dragon.jpg"),
        Book(name = "Moonrunner",                         coverUrl = "https://www.fightingfantasycollector.co.uk/FF48_Dragon_spine.jpg"),
        Book(name = "Siege of Sardath",                   coverUrl = "https://www.fightingfantasycollector.co.uk/FF49_Dragon_spine.jpg"),
        Book(name = "Return to Firetop Mountain",         coverUrl = "https://www.fightingfantasycollector.co.uk/FF50.jpg"),
        Book(name = "Island of the Undead",               coverUrl = "https://www.fightingfantasycollector.co.uk/FF51.jpg"),
        Book(name = "Night Dragon",                       coverUrl = "https://www.fightingfantasycollector.co.uk/FF52.jpg"),
        Book(name = "Spellbreaker",                       coverUrl = "https://www.fightingfantasycollector.co.uk/FF53.jpg"),
        Book(name = "Legend of Zagor",                    coverUrl = "https://www.fightingfantasycollector.co.uk/FF54.jpg"),
        Book(name = "Deathmoor",                          coverUrl = "https://www.fightingfantasycollector.co.uk/FF55.jpg"),
        Book(name = "Knights of Doom",                    coverUrl = "https://www.fightingfantasycollector.co.uk/FF56.jpg"),
        Book(name = "Magehunter",                         coverUrl = "https://www.fightingfantasycollector.co.uk/FF57.jpg"),
        Book(name = "Revenge of the Vampire",             coverUrl = "https://www.fightingfantasycollector.co.uk/FF58.jpg"),
        Book(name = "Curse of the Mummy",                 coverUrl = "https://www.fightingfantasycollector.co.uk/FF59.jpg"),
        Book(name = "Eye of the Dragon",                  coverUrl = "https://vignette.wikia.nocookie.net/fightingfantasy/images/b/bc/60_V2(W1)_01.jpg"),
        Book(name = "Bloodbones",                         coverUrl = "https://vignette.wikia.nocookie.net/fightingfantasy/images/a/a4/61_V2(W1)_01.jpg"),
        Book(name = "Howl of the Werewolf",               coverUrl = "https://vignette.wikia.nocookie.net/fightingfantasy/images/c/c5/HowlShield.jpg"),
        Book(name = "Stormslayer",                        coverUrl = "https://vignette.wikia.nocookie.net/fightingfantasy/images/1/15/StormslayerShield.jpg"),
        Book(name = "Night of the Necromancer",           coverUrl = "https://vignette.wikia.nocookie.net/fightingfantasy/images/1/1d/Ff7new_sml.jpg"),
        Book(name = "Blood of the Zombies",               coverUrl = "https://cdn1-www.gamerevolution.com/assets/uploads/2012/10/fighting-fantasy-blood-of-the-zombies.jpg"),
        Book(name = "Sorcery! The Shamutanti Hills",      coverUrl = "https://www.fightingfantasycollector.co.uk/Sorcery_1__Red.jpg"),
        Book(name = "Sorcery! Kharé - Cityport of Traps", coverUrl = "https://www.fightingfantasycollector.co.uk/Sorcery_2_Red.jpg"),
        Book(name = "Sorcery! The Seven Serpents",        coverUrl = "https://www.fightingfantasycollector.co.uk/Sorcery_3_Red.jpg"),
        Book(name = "Sorcery! The Crown of Kings",        coverUrl = "https://www.fightingfantasycollector.co.uk/Sorcery_4_Red.jpg")
    )

    val stats: List<Stat> = listOf(
        // Stats used in every book
        Stat(name = "Skill",   type = INT),
        Stat(name = "Stamina", type = INT),
        Stat(name = "Luck",    type = INT),
        
        // Stats used in more than one book
        Stat(name = "Equipment",                     type = TEXT),
        Stat(name = "Provisions",                    type = INT),
        Stat(name = "Gold",                          type = INT),
        Stat(name = "Jewels",                        type = TEXT),
        Stat(name = "Notes",                         type = TEXT),
        Stat(name = "Potions",                       type = TEXT),
        Stat(name = "Armour",                        type = INT),
        Stat(name = "Weapons Strength",              type = INT),
        Stat(name = "Shields",                       type = INT),
        Stat(name = "Money",                         type = INT),
        Stat(name = "Fear",                          type = INT),
        Stat(name = "Clues",                         type = TEXT),
        Stat(name = "Fuel",                          type = TEXT),
        Stat(name = "Credits",                       type = INT),
        Stat(name = "Oxygen",                        type = INT),
        Stat(name = "Treasure",                      type = TEXT),
        Stat(name = "Abilities",                     type = TEXT),
        Stat(name = "Spells",                        type = TEXT),
        Stat(name = "Honour",                        type = INT),
        Stat(name = "Time",                          type = INT),
        Stat(name = "Armour",                        type = TEXT),
        Stat(name = "Faith",                         type = INT),
        Stat(name = "Magic",                         type = INT),
        Stat(name = "Weapon",                        type = TEXT),
        Stat(name = "Poison",                        type = INT),
        Stat(name = "Codewords",                     type = TEXT),
        Stat(name = "Day of the Week",               type = MULTI_OPTION, possibleValues = Defined(listOf("Stormsday", "Moonsday", "Fireday", "Earthday", "Windsday", "Seaday", "Highday"))),
        Stat(name = "Medkit",                        type = INT),
        Stat(name = "Bonuses, Penalties and Curses", type = TEXT),
        Stat(name = "Libra - Goddess of Justice",    type = SINGLE_OPTION, possibleValues = Defined(listOf("Revitalization", "Escape", "Removal of Curses and Diseases"))),
        
        // The Citadel of Chaos
        Stat(name = "Spells", type = MULTI_OPTION_REPEAT, possibleValues = Defined(listOf("Creature Copy", "E.S.P.", "Fire", "Fool's Gold", "Illusion", "Levitation", "Luck", "Shielding", "Skill", "Stamina", "Strength", "Weakness"))),
        
        // Starship Traveller
        Stat(name = "Science Officer - Skill",       type = INT),
        Stat(name = "Science Officer - Stamina",     type = INT),
        Stat(name = "Medical Officer - Skill",       type = INT),
        Stat(name = "Medical Officer - Stamina",     type = INT),
        Stat(name = "Engineering Officer - Skill",   type = INT),
        Stat(name = "Engineering Officer - Stamina", type = INT),
        Stat(name = "Security Officer - Skill",      type = INT),
        Stat(name = "Security Officer - Stamina",    type = INT),
        Stat(name = "Security Guard 1 - Skill",      type = INT),
        Stat(name = "Security Guard 1 - Stamina",    type = INT),
        Stat(name = "Security Guard 2 - Skill",      type = INT),
        Stat(name = "Security Guard 2 - Stamina",    type = INT),
        
        // Scorpion Swamp
        Stat(name = "Spell Gems and Spells", type = MULTI_OPTION_REPEAT, possibleValues = Defined(listOf("Skill", "Stamina", "Luck", "Fire", "Ice", "Illusion", "Friendship", "Growth", "Bless", "Fear", "Withering", "Curse"))),
        
        // Space Assassin
        Stat(name = "Weapons",   type = MULTI_OPTION_REPEAT, possibleValues = Defined(listOf("Electric Lash", "Assault Blaster", "Grenade", "Gravity Bomb"))),
        Stat(name = "Pep Pills", type = INT),
        
        // Freeway Fighter
        Stat(name = "Firepower",         type = INT),
        Stat(name = "Rockets",           type = INT),
        Stat(name = "Iron Spikes",       type = INT),
        Stat(name = "Oil",               type = INT),
        Stat(name = "Car Modifications", type = TEXT),
        Stat(name = "Spare Wheels",      type = INT),
        
        // Temple of Terror
        Stat(name = "Spells", type = MULTI_OPTION, possibleValues = Defined(listOf("Open Door", "Creature Sleep", "Magic Arrow", "Language", "Read Symbols", "Light", "Fire", "Jump", "Detect Trap", "Create Water"))),
        
        // The Rings of Kether
        Stat(name = "Smart Missiles", type = INT),
        Stat(name = "Energy Tablets", type = INT),
        
        // Seas of Blood
        Stat(name = "Crew Strike",   type = INT),
        Stat(name = "Crew Strength", type = INT),
        Stat(name = "Booty",         type = TEXT),
        
        // Appointment with F.E.A.R.
        Stat(name = "Super Power", type = SINGLE_OPTION, possibleValues = Defined(listOf("Super Strength", "Psi-Powers", "Enhanced Technological Skill", "Energy Blast"))),
        Stat(name = "Hero Points", type = INT),
        
        // Rebel Planet
        Stat(name = "Code Clues", type = TEXT),
        
        // Sword of the Samurai
        Stat(name = "Special Skill", type = SINGLE_OPTION, possibleValues = Defined(listOf("Kyujutsu", "Iaijutsu", "Karumijutsu", "Ni-to-Kenjutsu"))),
        
        // Robot Commando
        Stat(name = "Robot",             type = TEXT),
        Stat(name = "Speed",             type = SINGLE_OPTION, possibleValues = Defined(listOf("Slow", "Medium", "Fast", "Very Fast"))),
        Stat(name = "Bonus",             type = INT),
        Stat(name = "Special Abilities", type = TEXT),
        
        // Beneath Nightmare Castle
        Stat(name = "Willpower", type = INT),
        
        // Star Strider
        Stat(name = "Calculations", type = TEXT),
        
        // Phantoms of Fear
        Stat(name = "Power", type = INT),

        // Midnight Rogue
        Stat(name = "Backpack Items", type = TEXT),
        Stat(name = "Special Skills", type = MULTI_OPTION, possibleValues = Defined(listOf("Climb", "Hide", "Pick Lock", "Pick Pocket", "Secret Signs", "Sneak", "Spot Hidden"))),
        
        // Chasms of Malice
        Stat(name = "Tabasha the Bazouk", type = TEXT),
        Stat(name = "Khuddam",            type = MULTI_OPTION, possibleValues = Defined(listOf("Geshrak", "Gurskut", "Friankara", "Barkek", "Griffkek", "Churka", "Kahhrac"))),
        Stat(name = "Cyphers",            type = TEXT),
        
        // Battleblade Warrior
        Stat(name = "Special Items", type = TEXT),
        
        // Sky Lord
        Stat(name = "Starhip", type = TEXT),
        Stat(name = "Rating",  type = INT),
        Stat(name = "Lasers",  type = INT),
        
        // Daggers of Darkness
        Stat(name = "Medallions", type = MULTI_OPTION, possibleValues = Defined(listOf("Yigenik", "Uruz", "Bogomil", "Hulugu", "Korkut", "Kazilik"))),
        
        // Armies of Death
        Stat(name = "Soldiers",     type = TEXT),
        Stat(name = "Situation",    type = SINGLE_OPTION, possibleValues = Defined(listOf("Superior", "Even", "Inferior"))),
        Stat(name = "Total Troops", type = INT),
        
        // Vault of the Vampire
        Stat(name = "Afflictions", type = TEXT),
        
        // Fangs of Fury
        Stat(name = "Citadel Walls", type = INT),
        Stat(name = "Cubes",         type = TEXT),
        Stat(name = "Gems",          type = TEXT),
        
        // Dead of Night
        Stat(name = "Talents",    type = MULTI_OPTION, possibleValues = Defined(listOf("Banish Undead", "Darkveil", "Heal", "Holy Circle", "Meditation", "Sense Demon", "Speak Demon"))),
        Stat(name = "Holy Water", type = INT),
        Stat(name = "Evil",       type = INT),
        
        // Master of Chaos
        Stat(name = "Skills",    type = MULTI_OPTION, possibleValues = Defined(listOf("Acute Hearing", "Animal Wisdom", "Blindsight", "Climbing", "Move Silently", "Tracking"))),
        Stat(name = "Notoriety", type = INT),
        
        // Keep of the Lich-Lord
        Stat(name = "Resolve",     type = INT),
        Stat(name = "Alarm value", type = INT),
        
        // Spectral Stalkers
        Stat(name = "Trail",                     type = INT),
        Stat(name = "Potions and Magical Items", type = TEXT),
        
        // Tower of Destruction
        Stat(name = "Enemy Encounter", type = TEXT),
        Stat(name = "Possessions",     type = TEXT),
        
        // The Crimson Tide
        Stat(name = "Ferocity", type = INT),
        Stat(name = "Age",      type = INT),
        
        // Moonrunner
        Stat(name = "Skills", type = MULTI_OPTION, possibleValues = Defined(listOf("Acrobatics", "Climb", "Combat", "Con", "Disguise", "Lock Picking", "Sleight of Hand", "Sneak", "Tracking"))),
        
        // Siege of Sardath
        Stat(name = "Arrows",           type = INT),
        Stat(name = "Bundles of Herbs", type = INT),
        
        // Island of the Undead
        Stat(name = "Presence", type = INT),
        
        // Night Dragon
        Stat(name = "Nemesis Points", type = INT),
        
        // Legend of Zagor
        Stat(name = "Talismans",     type = TEXT),
        Stat(name = "Daggers",       type = TEXT),
        Stat(name = "Advantages",    type = MULTI_OPTION, possibleValues = Defined(listOf("Can't be surprised", "Can use any weapons", "Add 2 to attack strength vs. stone monsters", "Add 2 to skill when testing spot skill"))),
        Stat(name = "Disadvantages", type = MULTI_OPTION, possibleValues = Defined(listOf("Can't wear plate mail", "No bonus to attack strength with chain mail", "Subtract 2 from attack strength with crossbow", "Can't use longbow or two-handed weapon", "Can't use metal armor, bow or two-handed weapon"))),
        
        // Knights of Doom
        Stat(name = "Special Skills", type = MULTI_OPTION, possibleValues = Defined(listOf("Battle Tactics", "Ride", "Target", "Tracking", "Weapon", "Arcane Lore", "Banish Spirit", "Commune", "Holy Strike"))),

        // Magehunter
        Stat(name = "Companion Skill",   type = INT),
        Stat(name = "Companion Stamina", type = INT),

        // Revenge of the Vampire
        Stat(name = "Blood Points", type = INT),

        // Howl of the Werewolf
        Stat(name = "Change", type = INT),

        // Stormslayer
        Stat(name = "Damage", type = INT),

        // Night of the Necromancer
        Stat(name = "Will",         type = INT),
        Stat(name = "Host Skill",   type = INT),
        Stat(name = "Host Stamina", type = INT),

        // Blood of the Zombies
        Stat(name = "Dollars",                        type = INT),
        Stat(name = "Grenades",                       type = INT),
        Stat(name = "Total Number of Zombies Killed", type = INT),
        Stat(name = "Number",                         type = INT)
    )

    val bookStats: List<BookStat> = listOf(
        BookStat(1, 1),
        BookStat(1, 2),
        BookStat(1, 3),
        BookStat(1, 4),
        BookStat(1, 5),
        BookStat(1, 6),
        BookStat(1, 7),
        BookStat(1, 8),
        BookStat(1, 9),

        BookStat(2, 1),
        BookStat(2, 2),
        BookStat(2, 3),
        BookStat(2, 4),
        BookStat(2, 6),
        BookStat(2, 8),
        BookStat(2, 26),
        BookStat(2, 34),

        BookStat(3, 1),
        BookStat(3, 2),
        BookStat(3, 3),
        BookStat(3, 4),
        BookStat(3, 5),
        BookStat(3, 6),
        BookStat(3, 7),
        BookStat(3, 8),
        BookStat(3, 9),

        BookStat(4, 1),
        BookStat(4, 2),
        BookStat(4, 3),
        BookStat(4, 35),
        BookStat(4, 36),
        BookStat(4, 37),
        BookStat(4, 38),
        BookStat(4, 39),
        BookStat(4, 40),
        BookStat(4, 41),
        BookStat(4, 42),
        BookStat(4, 43),
        BookStat(4, 44),
        BookStat(4, 45),
        BookStat(4, 46),
        BookStat(4, 11),
        BookStat(4, 12),

        BookStat(5, 1),
        BookStat(5, 2),
        BookStat(5, 3),
        BookStat(5, 4),
        BookStat(5, 5),
        BookStat(5, 6),
        BookStat(5, 7),
        BookStat(5, 8),
        BookStat(5, 9),

        BookStat(6, 1),
        BookStat(6, 2),
        BookStat(6, 3),
        BookStat(6, 4),
        BookStat(6, 5),
        BookStat(6, 6),
        BookStat(6, 7),
        BookStat(6, 8),
        BookStat(6, 9),

        BookStat(7, 1),
        BookStat(7, 2),
        BookStat(7, 3),
        BookStat(7, 4),
        BookStat(7, 5),
        BookStat(7, 6),
        BookStat(7, 7),
        BookStat(7, 8),
        BookStat(7, 9),

        BookStat(8, 1),
        BookStat(8, 2),
        BookStat(8, 3),
        BookStat(8, 4),
        BookStat(8, 47),

        BookStat(9, 1),
        BookStat(9, 2),
        BookStat(9, 3),
        BookStat(9, 4),
        BookStat(9, 5),
        BookStat(9, 6),
        BookStat(9, 7),
        BookStat(9, 8),
        BookStat(9, 9),

        BookStat(10, 1),
        BookStat(10, 2),
        BookStat(10, 3),
        BookStat(10, 4),
        BookStat(10, 8),
        BookStat(10, 14),

        BookStat(11, 1),
        BookStat(11, 2),
        BookStat(11, 3),
        BookStat(11, 4),
        BookStat(11, 5),
        BookStat(11, 6),
        BookStat(11, 7),
        BookStat(11, 8),
        BookStat(11, 9),

        BookStat(12, 1),
        BookStat(12, 2),
        BookStat(12, 3),
        BookStat(12, 4),
        BookStat(12, 10),
        BookStat(12, 48),
        BookStat(12, 49),

        BookStat(13, 1),
        BookStat(13, 2),
        BookStat(13, 3),
        BookStat(13, 4),
        BookStat(13, 31),
        BookStat(13, 17),
        BookStat(13, 50),
        BookStat(13, 51),
        BookStat(13, 52),
        BookStat(13, 53),
        BookStat(13, 54),
        BookStat(13, 55),
        BookStat(13, 10),
        BookStat(13, 16),

        BookStat(14, 1),
        BookStat(14, 2),
        BookStat(14, 3),
        BookStat(14, 4),
        BookStat(14, 5),
        BookStat(14, 6),
        BookStat(14, 56),

        BookStat(15, 1),
        BookStat(15, 2),
        BookStat(15, 3),
        BookStat(15, 4),
        BookStat(15, 11),
        BookStat(15, 12),
        BookStat(15, 57),
        BookStat(15, 58),
        BookStat(15, 13),

        BookStat(16, 1),
        BookStat(16, 2),
        BookStat(16, 3),
        BookStat(16, 4),
        BookStat(16, 59),
        BookStat(16, 60),
        BookStat(16, 61),

        BookStat(17, 1),
        BookStat(17, 2),
        BookStat(17, 3),
        BookStat(17, 15),
        BookStat(17, 62),
        BookStat(17, 63),

        BookStat(18, 1),
        BookStat(18, 2),
        BookStat(18, 3),
        BookStat(18, 4),
        BookStat(18, 13),
        BookStat(18, 64),

        BookStat(19, 1),
        BookStat(19, 2),
        BookStat(19, 3),
        BookStat(19, 4),
        BookStat(19, 5),
        BookStat(19, 6),
        BookStat(19, 7),
        BookStat(19, 8),
        BookStat(19, 9),

        BookStat(20, 1),
        BookStat(20, 2),
        BookStat(20, 3),
        BookStat(20, 5),
        BookStat(20, 8),
        BookStat(20, 22),
        BookStat(20, 65),

        BookStat(21, 1),
        BookStat(21, 2),
        BookStat(21, 3),
        BookStat(21, 4),
        BookStat(21, 8),

        BookStat(22, 1),
        BookStat(22, 2),
        BookStat(22, 3),
        BookStat(22, 4),
        BookStat(22, 10),
        BookStat(22, 66),
        BookStat(22, 67),
        BookStat(22, 68),
        BookStat(22, 69),
        BookStat(22, 31),

        BookStat(23, 1),
        BookStat(23, 2),
        BookStat(23, 3),
        BookStat(23, 4),
        BookStat(23, 5),
        BookStat(23, 6),
        BookStat(23, 7),
        BookStat(23, 8),
        BookStat(23, 9),

        BookStat(24, 1),
        BookStat(24, 2),
        BookStat(24, 3),
        BookStat(24, 4),
        BookStat(24, 8),

        BookStat(25, 1),
        BookStat(25, 2),
        BookStat(25, 3),
        BookStat(25, 4),
        BookStat(25, 5),
        BookStat(25, 6),
        BookStat(25, 9),
        BookStat(25, 70),

        BookStat(26, 1),
        BookStat(26, 2),
        BookStat(26, 3),
        BookStat(26, 4),
        BookStat(26, 8),
        BookStat(26, 19),

        BookStat(27, 1),
        BookStat(27, 2),
        BookStat(27, 3),
        BookStat(27, 23),
        BookStat(27, 18),
        BookStat(27, 14),
        BookStat(27, 15),
        BookStat(27, 71),

        BookStat(28, 1),
        BookStat(28, 2),
        BookStat(28, 3),
        BookStat(28, 4),
        BookStat(28, 5),
        BookStat(28, 8),
        BookStat(28, 9),
        BookStat(28, 72),

        BookStat(29, 1),
        BookStat(29, 2),
        BookStat(29, 3),
        BookStat(29, 4),
        BookStat(29, 5),
        BookStat(29, 8),
        BookStat(29, 73),
        BookStat(29, 74),

        BookStat(30, 1),
        BookStat(30, 2),
        BookStat(30, 3),
        BookStat(30, 5),
        BookStat(30, 75),
        BookStat(30, 76),
        BookStat(30, 77),
        BookStat(30, 16),
        BookStat(30, 20),
        BookStat(30, 21),

        BookStat(31, 1),
        BookStat(31, 2),
        BookStat(31, 3),
        BookStat(31, 4),
        BookStat(31, 5),
        BookStat(31, 78),

        BookStat(32, 1),
        BookStat(32, 2),
        BookStat(32, 3),
        BookStat(32, 4),
        BookStat(32, 5),
        BookStat(32, 6),
        BookStat(32, 7),
        BookStat(32, 8),
        BookStat(32, 9),
        BookStat(32, 23),

        BookStat(33, 1),
        BookStat(33, 2),
        BookStat(33, 3),
        BookStat(33, 4),
        BookStat(33, 5),
        BookStat(33, 8),
        BookStat(33, 12),
        BookStat(33, 17),
        BookStat(33, 18),
        BookStat(33, 79),
        BookStat(33, 80),
        BookStat(33, 81),

        BookStat(34, 1),
        BookStat(34, 2),
        BookStat(34, 3),
        BookStat(34, 4),
        BookStat(34, 5),
        BookStat(34, 8),
        BookStat(34, 19),

        BookStat(35, 1),
        BookStat(35, 2),
        BookStat(35, 3),
        BookStat(35, 4),
        BookStat(35, 5),
        BookStat(35, 6),
        BookStat(35, 8),
        BookStat(35, 20),
        BookStat(35, 21),
        BookStat(35, 28),
        BookStat(35, 82),

        BookStat(36, 1),
        BookStat(36, 2),
        BookStat(36, 3),
        BookStat(36, 6),
        BookStat(36, 19),
        BookStat(36, 83),
        BookStat(36, 84),
        BookStat(36, 85),

        BookStat(37, 1),
        BookStat(37, 2),
        BookStat(37, 3),
        BookStat(37, 4),
        BookStat(37, 5),
        BookStat(37, 6),
        BookStat(37, 9),

        BookStat(38, 1),
        BookStat(38, 2),
        BookStat(38, 3),
        BookStat(38, 4),
        BookStat(38, 5),
        BookStat(38, 8),
        BookStat(38, 19),
        BookStat(38, 25),
        BookStat(38, 21),
        BookStat(38, 86),

        BookStat(39, 1),
        BookStat(39, 2),
        BookStat(39, 3),
        BookStat(39, 4),
        BookStat(39, 5),
        BookStat(39, 6),
        BookStat(39, 8),
        BookStat(39, 87),
        BookStat(39, 88),
        BookStat(39, 89),

        BookStat(40, 1),
        BookStat(40, 2),
        BookStat(40, 3),
        BookStat(40, 4),
        BookStat(40, 5),
        BookStat(40, 6),
        BookStat(40, 8),
        BookStat(40, 90),
        BookStat(40, 91),
        BookStat(40, 92),

        BookStat(41, 1),
        BookStat(41, 2),
        BookStat(41, 3),
        BookStat(41, 4),
        BookStat(41, 5),
        BookStat(41, 8),
        BookStat(41, 93),
        BookStat(41, 94),
        BookStat(41, 19),

        BookStat(42, 1),
        BookStat(42, 2),
        BookStat(42, 3),
        BookStat(42, 4),
        BookStat(42, 5),
        BookStat(42, 8),
        BookStat(42, 19),

        BookStat(43, 1),
        BookStat(43, 2),
        BookStat(43, 3),
        BookStat(43, 4),
        BookStat(43, 5),
        BookStat(43, 8),
        BookStat(43, 19),
        BookStat(43, 95),
        BookStat(43, 96),

        BookStat(44, 1),
        BookStat(44, 2),
        BookStat(44, 3),
        BookStat(44, 4),
        BookStat(44, 5),
        BookStat(44, 6),
        BookStat(44, 8),
        BookStat(44, 24),
        BookStat(44, 27),

        BookStat(45, 1),
        BookStat(45, 2),
        BookStat(45, 3),
        BookStat(45, 4),
        BookStat(45, 5),
        BookStat(45, 6),
        BookStat(45, 27),
        BookStat(45, 97),
        BookStat(45, 98),

        BookStat(46, 1),
        BookStat(46, 2),
        BookStat(46, 3),
        BookStat(46, 4),
        BookStat(46, 5),
        BookStat(46, 22),
        BookStat(46, 23),
        BookStat(46, 99),
        BookStat(46, 100),

        BookStat(47, 1),
        BookStat(47, 2),
        BookStat(47, 3),
        BookStat(47, 4),
        BookStat(47, 5),
        BookStat(47, 8),
        BookStat(47, 101),
        BookStat(47, 102),
        BookStat(47, 13),

        BookStat(48, 1),
        BookStat(48, 2),
        BookStat(48, 3),
        BookStat(48, 4),
        BookStat(48, 5),
        BookStat(48, 6),
        BookStat(48, 8),
        BookStat(48, 103),

        BookStat(49, 1),
        BookStat(49, 2),
        BookStat(49, 3),
        BookStat(49, 4),
        BookStat(49, 8),
        BookStat(49, 6),
        BookStat(49, 104),
        BookStat(49, 105),
        BookStat(49, 30),

        BookStat(50, 1),
        BookStat(50, 2),
        BookStat(50, 3),
        BookStat(50, 4),
        BookStat(50, 19),
        BookStat(50, 24),
        BookStat(50, 27),

        BookStat(51, 1),
        BookStat(51, 2),
        BookStat(51, 3),
        BookStat(51, 4),
        BookStat(51, 5),
        BookStat(51, 106),

        BookStat(52, 1),
        BookStat(52, 2),
        BookStat(52, 3),
        BookStat(52, 4),
        BookStat(52, 5),
        BookStat(52, 19),
        BookStat(52, 22),
        BookStat(52, 23),
        BookStat(52, 107),

        BookStat(53, 1),
        BookStat(53, 2),
        BookStat(53, 3),
        BookStat(53, 4),
        BookStat(53, 5),
        BookStat(53, 6),
        BookStat(53, 8),
        BookStat(53, 19),
        BookStat(53, 25),

        BookStat(54, 1),
        BookStat(54, 2),
        BookStat(54, 3),
        BookStat(54, 5),
        BookStat(54, 6),
        BookStat(54, 8),
        BookStat(54, 19),
        BookStat(54, 26),
        BookStat(54, 108),
        BookStat(54, 109),
        BookStat(54, 110),
        BookStat(54, 111),

        BookStat(55, 1),
        BookStat(55, 2),
        BookStat(55, 3),
        BookStat(55, 4),
        BookStat(55, 5),
        BookStat(55, 6),
        BookStat(55, 8),
        BookStat(55, 9),

        BookStat(56, 1),
        BookStat(56, 2),
        BookStat(56, 3),
        BookStat(56, 4),
        BookStat(56, 6),
        BookStat(56, 8),
        BookStat(56, 22),
        BookStat(56, 23),
        BookStat(56, 27),
        BookStat(56, 112),

        BookStat(57, 1),
        BookStat(57, 2),
        BookStat(57, 3),
        BookStat(57, 4),
        BookStat(57, 5),
        BookStat(57, 8),
        BookStat(57, 113),
        BookStat(57, 114),
        BookStat(57, 13),

        BookStat(58, 1),
        BookStat(58, 2),
        BookStat(58, 3),
        BookStat(58, 4),
        BookStat(58, 5),
        BookStat(58, 19),
        BookStat(58, 25),
        BookStat(58, 115),

        BookStat(59, 1),
        BookStat(59, 2),
        BookStat(59, 3),
        BookStat(59, 4),
        BookStat(59, 5),
        BookStat(59, 6),
        BookStat(59, 8),
        BookStat(59, 19),
        BookStat(59, 28),

        BookStat(60, 1),
        BookStat(60, 2),
        BookStat(60, 3),
        BookStat(60, 4),
        BookStat(60, 8),

        BookStat(61, 1),
        BookStat(61, 2),
        BookStat(61, 3),
        BookStat(61, 4),
        BookStat(61, 5),
        BookStat(61, 6),
        BookStat(61, 8),
        BookStat(61, 23),
        BookStat(61, 29),

        BookStat(62, 1),
        BookStat(62, 2),
        BookStat(62, 3),
        BookStat(62, 4),
        BookStat(62, 5),
        BookStat(62, 6),
        BookStat(62, 8),
        BookStat(62, 29),
        BookStat(62, 116),

        BookStat(63, 1),
        BookStat(63, 2),
        BookStat(63, 3),
        BookStat(63, 4),
        BookStat(63, 5),
        BookStat(63, 6),
        BookStat(63, 8),
        BookStat(63, 9),
        BookStat(63, 23),
        BookStat(63, 29),
        BookStat(63, 30),
        BookStat(63, 117),

        BookStat(64, 1),
        BookStat(64, 2),
        BookStat(64, 3),
        BookStat(64, 4),
        BookStat(64, 29),
        BookStat(64, 118),
        BookStat(64, 119),
        BookStat(64, 120),

        BookStat(65, 2),
        BookStat(65, 4),
        BookStat(65, 8),
        BookStat(65, 27),
        BookStat(65, 31),
        BookStat(65, 121),
        BookStat(65, 122),
        BookStat(65, 123),
        BookStat(65, 124),

        BookStat(66, 1),
        BookStat(66, 2),
        BookStat(66, 3),
        BookStat(66, 4),
        BookStat(66, 5),
        BookStat(66, 6),
        BookStat(66, 19),
        BookStat(66, 32),
        BookStat(66, 33),

        BookStat(67, 1),
        BookStat(67, 2),
        BookStat(67, 3),
        BookStat(67, 4),
        BookStat(67, 5),
        BookStat(67, 6),
        BookStat(67, 19),
        BookStat(67, 32),
        BookStat(67, 33),

        BookStat(68, 1),
        BookStat(68, 2),
        BookStat(68, 3),
        BookStat(68, 4),
        BookStat(68, 5),
        BookStat(68, 6),
        BookStat(68, 19),
        BookStat(68, 32),
        BookStat(68, 33),

        BookStat(69, 1),
        BookStat(69, 2),
        BookStat(69, 3),
        BookStat(69, 4),
        BookStat(69, 5),
        BookStat(69, 6),
        BookStat(69, 19),
        BookStat(69, 32),
        BookStat(69, 33)
    )
}
